---
- hosts: all
  gather_facts: no
  tasks:
    - name: Read vars from secrets file
      include_vars: "{{ secrets_file }}"
      tags: always
      check_mode: no

- hosts: all
  gather_facts: yes
  become: true
  roles:
    - { role: common,  tags: ['common'] }
    - { role: tls,     tags: ['tls'] }
    - { role: hosts,   tags: ['hosts'] }
    - { role: rsyslog, tags: ['rsyslog'] }
  handlers:
    - include: roles/httpd/handlers/main.yml

- hosts: storage
  gather_facts: yes
  become: true
  roles:
    - { role: mysql,                   tags: ['mysql'] }

- hosts: loadbalancer
  gather_facts: true
  become: true
  roles:
    - { role: haproxy, tags: ['lb'] }

- hosts: php-apps:java-apps
  gather_facts: yes
  become: true
  roles:
    - httpd
  handlers:
    - include: roles/httpd/handlers/main.yml

- hosts: php-apps
  gather_facts: no
  become: true
  vars:
    env_lang: php
  roles:
    - { role: php56fpm,                          tags: ['php56fpm'] }
    - { role: static,                            tags: ['static'] }
    - { role: metadata,                          tags: ['static'] }
    - { role: welcome,                           tags: ['welcome'] }
    - { role: openconext-common,                 tags: ['eb','profile'] }
    - { role: engineblock,                       tags: ['eb'     ] }
    - { role: profile,                           tags: ['profile'] }
  handlers:
    - include: roles/httpd/handlers/main.yml

- hosts: java-apps
  gather_facts: true
  become: true
  vars:
    env_lang: java
  roles:
    - { role: tomcat,            tags: ['tomcat'] }
    - { role: java,              tags: ['java'] }
    - { role: shibboleth,        tags: ['shib'   ] }
    - { role: metadata-exporter, tags: ['metadata-exporter'] }
    - { role: teams-gui,         tags: ['teams', 'teams-gui' ] }
    - { role: teams-server,      tags: ['teams', 'teams-server' ] }
    - { role: mujina-idp,        tags: ['legacy' ] }
    - { role: mujina-sp,         tags: ['legacy' ] }
    - { role: attribute-aggregation-gui,    tags: ['attribute-aggregation', 'attribute-aggregation-gui'] }
    - { role: attribute-aggregation-server, tags: ['attribute-aggregation', 'attribute-aggregation-server'] }
    - { role: authz-server,      tags: ['oauth', 'authz-server'    ] }
    - { role: authz-admin,       tags: ['oauth', 'authz-admin'     ] }
    - { role: voot,              tags: ['oauth', 'voot'            ] }
    - { role: authz-playground,  tags: ['oauth', 'authz-playground'] }
    - { role: pdp-gui,           tags: ['pdp', 'pdp-gui'] }
    - { role: pdp-server,        tags: ['pdp', 'pdp-server'] }
    - { role: oidc,              tags: ['oidc'] }
    - { role: vm_only_oidc,      tags: ['oidc'] }
    - { role: mongo,             tags: ['mongo'] }
    - { role: manage-gui,        tags: ['manage', 'manage-gui'] }
    - { role: manage-server,     tags: ['manage', 'manage-server'] }
    - { role: vm_only_provision_manage_eb, tags: ['vm_only_provision_manage_eb'] }

  handlers:
    - include: roles/httpd/handlers/main.yml
